### ISSUE TITLE
Support for device level CUBLAS

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnativelib.jl#1]
Early support was added with 500d4716b60b64a246441f3184ba499d3f6a7e5c, but this currently only includes the helper function an non of the actual kernel functions.

This relies on stack allocation within C++ and then returning the struct to Julia (I have to check that this generates correct code)

Ideally the code would look more like this:

``` julia
cublasCreate(handle) = icxx"cublasCreate($handle);"
@target ptx function f()
   r_handle = Ref{cublasHandle_t}()
   cublasCreate(r_handle)
   handle = r_handle[]
 end
```

But this won't work till we have stack allocated references... curand.jl works around this by doing heap allocation.

@MichaelOhlrogge this is still a WIP and I have to figure out the proper way for a few thins, but let me know what you think.
## TODO:
- [ ] Verify that the current approach with stack allocation (in C++) and returning values works. (It probably doesn't) Ideally we have stack allocation support in Julia
- [ ] Link against cublas_static.a
- [ ] Implement Level 1
- [ ] Implement Level 2
- [ ] Implement Level 3
- [ ] Expose higlevel api similar to CUBLAS.jl

@kshyatt If Cxx.jl wouldn't be such a heavy dependency we could use exactly the same code for CUBLAS.jl proper.

**Comment by MichaelOhlrogge** [comment]
I think it looks good.  I haven't been directly able to test it out yet since I am still working on getting my SysAdmin to install the version of Julia needed for CUDAnative (which, by the way, does seem like a very promising project).  Nevertheless, I like the look of the way that the interface works a lot.  The ability to specifically control and call from Julia the things like the creation of handles and streams is very promising in terms of giving the user the kind of detailed control of what is going on that they would want, "all from the comfort" of working inside of Julia.  I also use CUSPARSE a lot, and the interface for that is almost identical as for CUBLAS, so this is nice to see too because it would generalize quite well.  Thanks!

**Comment by kshyatt** [comment]
@vchuravy do you want me to wrap level 1 following your example for the helper?

**Comment by vchuravy** [comment]
That would be cool. I am fighting with stack-allocation and return-by-value. Otherwise the example code won't properly work and we need to heap allocate the state (slow...)
